# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: app-config
#   namespace: react-kub-app
#   labels:
#     app: react-kub-app
# data:
#   # Backend configuration
#   BACKEND_PORT: "5000"
#   BACKEND_HOST: "0.0.0.0"
#   # Frontend configuration
# VITE_API_BASE:  "http://localhost:5000"

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: react-kub-app
  labels:
    app: react-kub-app
data:
  BACKEND_PORT: "5000"
  BACKEND_HOST: "backend" #"0.0.0.0"
  VITE_API_BASE: "http://backend:5000"  #For LoadBalancer
  # VITE_API_BASE: "http://localhost:30500"
  # VITE_API_BASE: "http://localhost:5000"
